### PR TITLE
fix(operation-name): get graphql operation name from context.

### PR DESCRIPTION
**Pull request by hsblhsn**
- fix(operation-name): get graphql operation name from context.
- chore(dependency): upgrade dependencies using `go get -u all`

previously it was reporting the first operation name in the query even the running query is different.

The bug was something like this:

```graphql
query A {
   __typename
}
query B {
   __typename
}
query C {
   __typename
}
```
Even if I run the operation `C`, it was always reporting `A` as operation name.

This PR fixes the bug 🚀

### CODE REVIEW

**Comment by hsblhsn** [comment]
@ravilushqa can you have a look at why the CI is failing? 🙏

**Comment by ravilushqa** [comment]
> @ravilushqa can you have a look at why the CI is failing? 🙏

@hsblhsn thanks for the PR, I will try to check the PR in a few days

**Comment by ravilushqa** [comment]
@hsblhsn you updated deps in root, looks like you need to update deps also in example folder, then ci should be passed.
Also would be great if you will add test for your scenario

**Comment by hsblhsn** [comment]
Hi @ravilushqa,

Thank you! The CI has been fixed. And I have also added a test for the changes. If everything is fine, please create a release after merging :) 

Thanks 🙏

**Pull request merged**
